name: Frontend CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/frontend-job-aggregator/**'
      - '.github/workflows/frontend.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'frontend/frontend-job-aggregator/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: Install dependencies
        run: |
          cd frontend/frontend-job-aggregator
          npm install
          
      - name: Build
        run: |
          cd frontend/frontend-job-aggregator
          npm run build
          
      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@v4
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
