name: Frontend CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/frontend-job-aggregator/**'
      - '.github/workflows/frontend.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'frontend/frontend-job-aggregator/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: Install dependencies
        run: |
          cd frontend/frontend-job-aggregator
          npm install
          
      - name: Build
        run: |
          cd frontend/frontend-job-aggregator
          npm run build
        env:
          VITE_API_USER_SERVICE: ${{ secrets.VITE_API_USER_SERVICE }}
          VITE_API_JOBS_SERVICE: ${{ secrets.VITE_API_JOBS_SERVICE }}
          VITE_API_MATCHING_SERVICE: ${{ secrets.VITE_API_MATCHING_SERVICE }}
          VITE_API_TEXT_PROCESSING: ${{ secrets.VITE_API_TEXT_PROCESSING }}
          VITE_API_IRISHJOBS: ${{ secrets.VITE_API_IRISHJOBS }}
          VITE_API_JOBSIE: ${{ secrets.VITE_API_JOBSIE }}
          VITE_GOOGLE_CLIENT_ID: ${{ secrets.VITE_GOOGLE_CLIENT_ID }}
          VITE_REDIRECT_URI: ${{ secrets.VITE_REDIRECT_URI }}
          
      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: frontend/frontend-job-aggregator/dist
          branch: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}
